FROM golang:1.24.0-bookworm AS builder

ARG GIT_BRANCH

WORKDIR /app
RUN git fetch origin && git checkout ${GIT_BRANCH}
COPY ../app /app
RUN go mod tidy && go build -o server .

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/server /app/bin/server

RUN chmod +x /app/bin/server

EXPOSE 3333

ENTRYPOINT ["/app/bin/server"]
