FROM python:3.13.2-slim-bookworm

ARG GIT_BRANCH

WORKDIR /data
RUN git fetch origin && git checkout ${GIT_BRANCH}
COPY ../data /data
RUN python -m venv venv && venv/bin/pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["venv/bin/python", "insert_data_mongo.py"]
CMD ["mongo", "27017", "pokemon", "kanto", "csv/pokemon_kanto.csv", "y"]
